# Generated by Django 4.1.5 on 2023-01-28 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронный почтовый адрес')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фио')),
                ('comment', models.TextField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='SendingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время последней попытки')),
                ('attempt_status', models.CharField(blank=True, max_length=250, null=True, verbose_name='Статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тема письма')),
                ('content', models.CharField(max_length=500, verbose_name='Тело письма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_mail.client', verbose_name='Адресат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_time', models.TimeField(blank=True, null=True, verbose_name='Время рассылки')),
                ('periodicity', models.CharField(blank=True, choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], max_length=50, null=True, verbose_name='Периодичность')),
                ('mail_status', models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена')], default='Создана', max_length=10, verbose_name='Статус рассылки')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Начальная дата')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Конечная дата')),
                ('mailing_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_mail.sendingattempt', verbose_name='Попытка Рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_mail.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
