# Generated by Django 4.1.5 on 2023-01-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client',
        ),
        migrations.AddField(
            model_name='message',
            name='client',
            field=models.ManyToManyField(to='my_mail.client', verbose_name='Адресат'),
        ),
    ]
