# Generated by Django 4.1.5 on 2023-01-28 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_mail', '0003_remove_message_client_mailinglist_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='mailing_attempt',
        ),
        migrations.AddField(
            model_name='sendingattempt',
            name='mailing_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_mail.mailinglist', verbose_name='Список Рассылки'),
        ),
    ]
